"""
Blessed Hubspot connector for Airbyte SDK.

Auto-generated from OpenAPI specification.
"""

from .connector import HubspotConnector
from .models import (
    HubspotAuthConfig,
    ContactProperties,
    Contact,
    PagingNext,
    Paging,
    ContactsList,
    CompanyProperties,
    Company,
    CompaniesList,
    DealProperties,
    Deal,
    DealsList,
    TicketProperties,
    Ticket,
    TicketsList,
    SchemaLabels,
    SchemaAssociationsItem,
    SchemaPropertiesItemModificationmetadata,
    SchemaPropertiesItem,
    Schema,
    SchemasList,
    CRMObjectProperties,
    CRMObject,
    ObjectsList,
    ContactsListResultMeta,
    ContactsSearchResultMeta,
    CompaniesListResultMeta,
    CompaniesSearchResultMeta,
    DealsListResultMeta,
    DealsSearchResultMeta,
    TicketsListResultMeta,
    TicketsSearchResultMeta,
    SchemasListResultMeta,
    ObjectsListResultMeta,
    HubspotExecuteResult,
    HubspotExecuteResultWithMeta,
    ContactsListResult,
    ContactsSearchResult,
    CompaniesListResult,
    CompaniesSearchResult,
    DealsListResult,
    DealsSearchResult,
    TicketsListResult,
    TicketsSearchResult,
    SchemasListResult,
    ObjectsListResult
)
from .types import (
    ContactsSearchParamsFiltergroupsItemFiltersItem,
    ContactsSearchParamsFiltergroupsItem,
    ContactsSearchParamsSortsItem,
    CompaniesSearchParamsFiltergroupsItemFiltersItem,
    CompaniesSearchParamsFiltergroupsItem,
    CompaniesSearchParamsSortsItem,
    DealsSearchParamsFiltergroupsItemFiltersItem,
    DealsSearchParamsFiltergroupsItem,
    DealsSearchParamsSortsItem,
    TicketsSearchParamsFiltergroupsItemFiltersItem,
    TicketsSearchParamsFiltergroupsItem,
    TicketsSearchParamsSortsItem,
    ContactProperties,
    CompanyProperties,
    DealProperties,
    TicketProperties,
    SchemaLabels,
    SchemaPropertiesItemModificationmetadata,
    SchemaPropertiesItem,
    SchemaAssociationsItem,
    CRMObjectProperties,
    PagingNext,
    ContactsListParams,
    ContactsGetParams,
    ContactsSearchParams,
    CompaniesListParams,
    CompaniesGetParams,
    CompaniesSearchParams,
    DealsListParams,
    DealsGetParams,
    DealsSearchParams,
    TicketsListParams,
    TicketsGetParams,
    TicketsSearchParams,
    SchemasListParams,
    SchemasGetParams,
    ObjectsListParams,
    ObjectsGetParams
)

__all__ = ["HubspotConnector", "HubspotAuthConfig", "ContactProperties", "Contact", "PagingNext", "Paging", "ContactsList", "CompanyProperties", "Company", "CompaniesList", "DealProperties", "Deal", "DealsList", "TicketProperties", "Ticket", "TicketsList", "SchemaLabels", "SchemaAssociationsItem", "SchemaPropertiesItemModificationmetadata", "SchemaPropertiesItem", "Schema", "SchemasList", "CRMObjectProperties", "CRMObject", "ObjectsList", "ContactsListResultMeta", "ContactsSearchResultMeta", "CompaniesListResultMeta", "CompaniesSearchResultMeta", "DealsListResultMeta", "DealsSearchResultMeta", "TicketsListResultMeta", "TicketsSearchResultMeta", "SchemasListResultMeta", "ObjectsListResultMeta", "HubspotExecuteResult", "HubspotExecuteResultWithMeta", "ContactsListResult", "ContactsSearchResult", "CompaniesListResult", "CompaniesSearchResult", "DealsListResult", "DealsSearchResult", "TicketsListResult", "TicketsSearchResult", "SchemasListResult", "ObjectsListResult", "ContactsSearchParamsFiltergroupsItemFiltersItem", "ContactsSearchParamsFiltergroupsItem", "ContactsSearchParamsSortsItem", "CompaniesSearchParamsFiltergroupsItemFiltersItem", "CompaniesSearchParamsFiltergroupsItem", "CompaniesSearchParamsSortsItem", "DealsSearchParamsFiltergroupsItemFiltersItem", "DealsSearchParamsFiltergroupsItem", "DealsSearchParamsSortsItem", "TicketsSearchParamsFiltergroupsItemFiltersItem", "TicketsSearchParamsFiltergroupsItem", "TicketsSearchParamsSortsItem", "ContactProperties", "CompanyProperties", "DealProperties", "TicketProperties", "SchemaLabels", "SchemaPropertiesItemModificationmetadata", "SchemaPropertiesItem", "SchemaAssociationsItem", "CRMObjectProperties", "PagingNext", "ContactsListParams", "ContactsGetParams", "ContactsSearchParams", "CompaniesListParams", "CompaniesGetParams", "CompaniesSearchParams", "DealsListParams", "DealsGetParams", "DealsSearchParams", "TicketsListParams", "TicketsGetParams", "TicketsSearchParams", "SchemasListParams", "SchemasGetParams", "ObjectsListParams", "ObjectsGetParams"]
