openapi: 3.1.0
info:
  title: Stripe API Connector
  version: 0.0.1
  x-airbyte-connector-name: stripe
  x-airbyte-external-documentation-urls:
    - title: Stripe API Changelog documentation
      type: changelog
      url: "https://docs.stripe.com/changelog"
    - title: Stripe API Upgrades documentation
      type: migration_guide
      url: "https://docs.stripe.com/upgrades"
    - title: Stripe API Versioning documentation
      type: api_release_history
      url: "https://docs.stripe.com/api/versioning"
    - title: Stripe API Reference documentation
      type: api_reference
      url: "https://docs.stripe.com/api"
    - title: Stripe API Authentication documentation
      type: authentication_guide
      url: "https://docs.github.com/rest/overview/authenticating-to-the-rest-api"

servers:
  - url: https://api.stripe.com
    description: Stripe API Server

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: API Key authentication using Bearer token

  schemas:
    Customer:
      type: object
      x-airbyte-entity-name: customers
      properties:
        id:
          type: string
          description: Unique identifier for the customer
        object:
          type: string
          description: String representing the object's type
          enum: [customer]
        email:
          type: string
          format: email
          description: Customer's email address
        name:
          type: string
          description: Customer's full name
        description:
          type: string
          description: An arbitrary string attached to the customer
        phone:
          type: string
          description: Customer's phone number
        address:
          type: object
          description: Customer's address
          properties:
            line1:
              type: string
            line2:
              type: string
            city:
              type: string
            state:
              type: string
            postal_code:
              type: string
            country:
              type: string
        metadata:
          type: object
          additionalProperties:
            type: string
          description: Set of key-value pairs for storing additional information
        created:
          type: integer
          format: int64
          description: Time at which the customer was created (Unix timestamp)
        balance:
          type: integer
          description: Current balance, if any
        delinquent:
          type: boolean
          description: Whether the customer has a delinquent balance
      required:
        - id
        - object

    CustomerList:
      type: object
      properties:
        object:
          type: string
          enum: [list]
        data:
          type: array
          items:
            $ref: "#/components/schemas/Customer"
        has_more:
          type: boolean
        url:
          type: string

paths:
  /v1/customers:
    get:
      summary: List all customers
      description: Returns a list of customers
      operationId: Customers_List
      x-airbyte-entity: customers
      x-airbyte-action: list
      tags:
        - Customers
      parameters:
        - name: limit
          in: query
          description: A limit on the number of objects to be returned
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
        - name: starting_after
          in: query
          description: A cursor for use in pagination
          schema:
            type: string
        - name: ending_before
          in: query
          description: A cursor for use in pagination
          schema:
            type: string
        - name: email
          in: query
          description: Filter customers by email address
          schema:
            type: string
      responses:
        "200":
          description: List of customers
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerList"

  /v1/customers/{id}:
    get:
      summary: Get a customer
      description: Gets the details of an existing customer
      operationId: Customers_Get
      x-airbyte-entity: customers
      x-airbyte-action: get
      tags:
        - Customers
      parameters:
        - name: id
          in: path
          required: true
          description: The customer ID
          schema:
            type: string
      responses:
        "200":
          description: Customer retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
